openapi: 3.0.0
info:
  title: zhihu_caffe
  version: 0.0.3
  contact: {}
paths:
  /users/signup:
    get:
      summary: ''
      description: ''
      parameters:
        - name: newUser
          in: header
          required: true
          schema:
            type: string
      operationId: userSignup
      responses:
        default:
          description: Default response
      tags:
        - user
  /users/logout:
    get:
      summary: ''
      description: ''
      parameters:
        - name: token
          in: cookie
          required: false
          schema:
            type: string
      operationId: userLogout
      responses:
        default:
          description: Default response
      tags:
        - user
  /users/login:
    post:
      summary: ''
      description: ''
      parameters:
        - name: id
          in: header
          required: true
          schema:
            type: string
          description: ''
        - name: password
          in: header
          required: true
          schema:
            type: string
          description: ''
      operationId: userLogin
      responses:
        default:
          description: Default response
      tags:
        - user
  '/users/{userid}':
    get:
      summary: get user profile by userid
      description: ''
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      operationId: getUserProfile
      responses:
        default:
          description: Default response
      tags:
        - user
    put:
      summary: update an existed user info by userid
      description: ''
      parameters:
        - name: userInfo
          in: header
          required: true
          schema:
            type: string
        - name: userid
          in: path
          required: true
          schema:
            type: string
      operationId: updateUser
      responses:
        default:
          description: Default response
      tags:
        - user
    delete:
      summary: delete an existed user by userid
      description: ''
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: integer
      operationId: deleteUser
      responses:
        default:
          description: Default response
      tags:
        - user
  /api/users:
    get:
      summary: get user list
      description: Returns a list containing all users.
      parameters: []
      operationId: getUsers
      responses:
        '200':
          description: Default response
          content:
            application/json:
              schema: {}
      tags:
        - user
  '/api/users/{userid}':
    get:
      summary: ''
      description: ''
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      operationId: getUserInfo
      responses:
        '200':
          description: Default response
          content:
            application/json:
              schema: {}
      tags:
        - user
  '/api/users/{userid}/articles':
    get:
      summary: get articles list written by a user with specified user id
      description: ''
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      operationId: getArticles
      responses:
        '200':
          description: Default response
          content:
            application/json:
              schema: {}
      tags:
        - article
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        password:
          type: string
          format: password
        articles:
          type: array
          xml:
            name: Article
            wrapped: true
          items:
            $ref: '#/components/schemas/Article'
        email:
          type: string
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        readNum:
          type: integer
          format: int64
        likeNum:
          type: integer
          format: int64
        content:
          type: string
        replies:
          type: array
          xml:
            name: Reply
            wrapped: true
          items:
            $ref: '#/components/schemas/Reply'
        tags:
          type: array
          xml:
            name: Tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
    Reply:
      type: object
      properties:
        id:
          type: integer
          format: int64
        likeNum:
          type: integer
          format: int64
        createTime:
          type: string
          format: date-time
        content:
          type: string
        author-url:
          type: string
    Tag:
      type: object
      properties:
        name:
          type: string
tags:
  - name: user
    description: |
      In the app, user can post articles or reply an article.
  - name: article
    description: >-
      An article can present infomation to other users, and users can interact
      with other users through this article.
  - name: tag
    description: 'Tag is used to describe an article, and also be used to search articles.'
  - name: replay
    description: >-
      Replay can be posted by a user after reading an article. Other users can
      also interact with replay.
