openapi: 3.0.0
info:
  title: Swagger Petstore
  version: 0.0.2
  contact: {}
paths:
  /user:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: getUser
      responses:
        default:
          description: Default response
      tags:
        - user
  /user/Logout:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: userLogout
      responses:
        default:
          description: Default response
      tags:
        - user
  /atricle:
    post:
      summary: ''
      description: ''
      parameters:
        - name: text
          in: query
          required: false
          schema:
            type: string
          description: 文本信息
        - name: figure
          in: query
          required: false
          schema:
            type: string
          description: 图片信息
        - name: ID
          in: query
          required: false
          schema:
            type: string
          description: 发送方用户ID
        - name: time
          in: query
          required: false
          schema:
            type: string
          description: 发送文章的时间
          # format: date-time
      operationId: sendArtical
      responses:
        default:
          description: Default response
      tags:
        - artical
    x-temp:
      summary: ''
      description: ''
      parameters: []
      operationId: getArtical
      responses:
        default:
          description: Default response
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: getArtical
      responses:
        default:
          description: Default response
      tags:
        - artical
  /user/Login:
    post:
      summary: ''
      description: ''
      parameters:
        - name: ID
          in: query
          required: false
          schema:
            type: string
          description: 用户ID
        - name: password
          in: query
          required: false
          schema:
            type: string
          description: 用户密码
          # format: password
      operationId: userLogin
      responses:
        default:
          description: Default response
      tags:
        - user
security: []
servers: []
components:
  links: {}
  callbacks: {}
  schemas:
    User:
      type: object
      properties:
        ID:
          type: string
        password:
          type: string
    #     article:
    #       articleID: []
    #     comment:
    #       commentID: []
    #     like:
    #       articleID: []
    # Article:
    #   type: object
    #   articleID:
    #     ID: []
    #     text: string
    #   userID:
    #     ID: []
tags:
  - name: user
    description: 用户操作
  - name: artical
    description: 文章操作
