openapi: 3.0.0
info:
  title: zhihu_caffe
  version: 0.0.3
  contact: {}
paths:
  /users:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: getUsers
      responses:
        default:
          description: Default response
      tags:
        - user
  /users/logout:
    get:
      summary: ''
      description: ''
      parameters:
        - name: token
          in: query
          required: false
          schema:
            type: string
      operationId: userLogout
      responses:
        default:
          description: Default response
      tags:
        - user
  /users/login:
    post:
      summary: ''
      description: ''
      parameters:
        - name: id
          in: query
          required: false
          schema:
            type: string
          description: ''
        - name: password
          in: query
          required: false
          schema:
            type: string
          description: ''
      operationId: userLogin
      responses:
        default:
          description: Default response
      tags:
        - user
  '/users/{user}':
    get:
      summary: ''
      description: ''
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: string
      operationId: ''
      responses:
        default:
          description: Default response
  '/users/{user}/articles':
    post:
      summary: ''
      description: ''
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: string
        - name: text
          in: query
          required: false
          schema:
            type: string
          description: 文本信息
        - name: figure
          in: query
          required: false
          schema:
            type: string
          description: 图片信息
        - name: ID
          in: query
          required: false
          schema:
            type: string
          description: 发送方用户ID
        - name: time
          in: query
          required: false
          schema:
            type: string
          description: 发送文章的时间
      operationId: sendArtical
      responses:
        default:
          description: Default response
      tags:
        - artical
    x-temp:
      summary: ''
      description: ''
      parameters: []
      operationId: getArtical
      responses:
        default:
          description: Default response
    get:
      summary: ''
      description: ''
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: string
      operationId: getArtical
      responses:
        default:
          description: Default response
      tags:
        - artical
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        password:
          type: string
          format: password
        articles:
          type: array
          xml:
            name: Article
            wrapped: true
          items:
            $ref: '#/components/schemas/Article'
        email:
          type: string
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        readNum:
          type: integer
          format: int64
        likeNum:
          type: integer
          format: int64
        content:
          type: string
        replies:
          type: array
          xml:
            name: Reply
            wrapped: true
          items:
            $ref: '#/components/schemas/Reply'
        tags:
          type: array
          xml:
            name: Tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
    Reply:
      type: object
      properties:
        id:
          type: integer
          format: int64
        likeNum:
          type: integer
          format: int64
        createTime:
          type: string
          format: date-time
        content:
          type: string
        author-url:
          type: string
    Tag:
      type: object
      properties:
        name:
          type: string
tags:
  - name: user
    description: |
      In the app, user can post articles or reply an article.
  - name: artical
    description: >-
      An article can present infomation to other users, and users can interact
      with other users through this article.
  - name: tag
    description: 'Tag is used to describe an article, and also be used to search articles.'
  - name: replay
    description: >-
      Replay can be posted by a user after reading an article. Other users can
      also interact with replay.
