/**
 * Zhihu_Caffe
 * Zhihu_Caffe can craw data from ZhihuDaily and post article by user,  allowing users to reply the article and interact with other users.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Reply from './Reply';

/**
* The Replies model module.
* @module model/Replies
* @version 0.1.4
*/
export default class Replies extends Array {
    /**
    * Constructs a new <code>Replies</code>.
    * @alias module:model/Replies
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>Replies</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Replies} obj Optional instance to populate.
    * @return {module:model/Replies} The populated <code>Replies</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Replies();
            ApiClient.constructFromObject(data, obj, 'Reply');
            
            
        }
        return obj;
    }





}
