/**
 * Zhihu_Caffe
 * Zhihu_Caffe can craw data from ZhihuDaily and post article by user,  allowing users to reply the article and interact with other users.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Reply model module.
* @module model/Reply
* @version 0.1.4
*/
export default class Reply {
    /**
    * Constructs a new <code>Reply</code>.
    * @alias module:model/Reply
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Reply</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Reply} obj Optional instance to populate.
    * @return {module:model/Reply} The populated <code>Reply</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Reply();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('likeNum')) {
                obj['likeNum'] = ApiClient.convertToType(data['likeNum'], 'Number');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('author-url')) {
                obj['author-url'] = ApiClient.convertToType(data['author-url'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Number} likeNum
    */
    'likeNum' = undefined;
    /**
    * @member {Date} createTime
    */
    'createTime' = undefined;
    /**
    * @member {String} content
    */
    'content' = undefined;
    /**
    * @member {String} author-url
    */
    'author-url' = undefined;
    /**
    * @member {String} url
    */
    'url' = undefined;




}
