/**
 * Zhihu_Caffee
 * Zhihu_Caffee can craw data from ZhihuDaily and post article by user,  allowing users to reply the article and interact with other users.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZhihuCaffe);
  }
}(this, function(expect, ZhihuCaffe) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZhihuCaffe.Apis();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Apis', function() {
    it('should create an instance of Apis', function() {
      // uncomment below and update the code to test Apis
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be.a(ZhihuCaffe.Apis);
    });

    it('should have the property usersUrl (base name: "users_url")', function() {
      // uncomment below and update the code to test the property usersUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property userUrl (base name: "user_url")', function() {
      // uncomment below and update the code to test the property userUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property articlesUrl (base name: "articles_url")', function() {
      // uncomment below and update the code to test the property articlesUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property articleUrl (base name: "article_url")', function() {
      // uncomment below and update the code to test the property articleUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property repliesUrl (base name: "replies_url")', function() {
      // uncomment below and update the code to test the property repliesUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property replyUrl (base name: "reply_url")', function() {
      // uncomment below and update the code to test the property replyUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property tagsUrl (base name: "tags_url")', function() {
      // uncomment below and update the code to test the property tagsUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

    it('should have the property tagUrl (base name: "tag_url")', function() {
      // uncomment below and update the code to test the property tagUrl
      //var instane = new ZhihuCaffe.Apis();
      //expect(instance).to.be();
    });

  });

}));
