openapi: 3.0.0
info:
  title: Swagger Petstore
  contact: {}
  version: 0.0.2
servers:
- url: /
tags:
- name: user
  description: 用户操作
- name: artical
  description: 文章操作
paths:
  /user:
    get:
      tags:
      - user
      operationId: getUser
      parameters: []
      responses:
        default:
          description: Default response
  /user/Logout:
    get:
      tags:
      - user
      operationId: userLogout
      parameters: []
      responses:
        default:
          description: Default response
  /atricle:
    get:
      tags:
      - artical
      operationId: getArtical
      parameters: []
      responses:
        default:
          description: Default response
    post:
      tags:
      - artical
      operationId: sendArtical
      parameters:
      - name: text
        in: query
        description: 文本信息
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: figure
        in: query
        description: 图片信息
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: ID
        in: query
        description: 发送方用户ID
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: time
        in: query
        description: 发送文章的时间
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    x-temp:
      summary: ""
      description: ""
      parameters: []
      operationId: getArtical
      responses:
        default:
          description: Default response
  /user/Login:
    post:
      tags:
      - user
      operationId: userLogin
      parameters:
      - name: ID
        in: query
        description: 用户ID
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: 用户密码
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: Default response
components:
  schemas:
    User:
      type: object
      properties:
        ID:
          type: string
        password:
          type: string
  links: {}
  callbacks: {}
