openapi: 3.0.0
info:
  title: zhihu_caffe
  contact: {}
  version: 0.0.2
servers:
- url: /
tags:
- name: user
  description: |
    In the app, user can post articles or reply an article.
- name: artical
  description: An article can present infomation to other users, and users can interact
    with other users through this article.
- name: tag
  description: Tag is used to describe an article, and also be used to search articles.
- name: replay
  description: Replay can be posted by a user after reading an article. Other users
    can also interact with replay.
paths:
  /user:
    get:
      tags:
      - user
      operationId: getUser
      parameters: []
      responses:
        default:
          description: Default response
  /user/Logout:
    get:
      tags:
      - user
      operationId: userLogout
      parameters: []
      responses:
        default:
          description: Default response
  /atricle:
    get:
      tags:
      - artical
      operationId: getArtical
      parameters: []
      responses:
        default:
          description: Default response
    post:
      tags:
      - artical
      operationId: sendArtical
      parameters:
      - name: text
        in: query
        description: 文本信息
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: figure
        in: query
        description: 图片信息
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: ID
        in: query
        description: 发送方用户ID
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: time
        in: query
        description: 发送文章的时间
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    x-temp:
      summary: ""
      description: ""
      parameters: []
      operationId: getArtical
      responses:
        default:
          description: Default response
  /user/Login:
    post:
      tags:
      - user
      operationId: userLogin
      parameters:
      - name: ID
        in: query
        description: 用户ID
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: 用户密码
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: Default response
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        password:
          type: string
          format: password
        articles:
          type: array
          xml:
            name: Article
            wrapped: true
          items:
            $ref: '#/components/schemas/Article'
        email:
          type: string
    Article:
      type: object
      properties:
        readNum:
          type: integer
          format: int32
        likeNum:
          type: integer
          format: int32
        content:
          type: string
        replies:
          type: array
          xml:
            name: Reply
            wrapped: true
          items:
            $ref: '#/components/schemas/Reply'
        tags:
          type: array
          xml:
            name: Tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
    Reply:
      type: object
      properties:
        likeNum:
          type: integer
          format: int32
        createTime:
          type: string
          format: date-time
        content:
          type: string
        author-url:
          type: string
    Tag:
      type: object
      properties:
        name:
          type: string
  links: {}
  callbacks: {}
