/**
 * Zhihu_Caffe
 * Zhihu_Caffe can craw data from ZhihuDaily and post article by user,  allowing users to reply the article and interact with other users.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Apis from './model/Apis';
import Article from './model/Article';
import Articles from './model/Articles';
import Replies from './model/Replies';
import Reply from './model/Reply';
import Tag from './model/Tag';
import Tags from './model/Tags';
import User from './model/User';
import Users from './model/Users';
import ArticleApi from './api/ArticleApi';
import DefaultApi from './api/DefaultApi';
import ReplyApi from './api/ReplyApi';
import TagApi from './api/TagApi';
import UserApi from './api/UserApi';

/**
* Zhihu_Caffe_can_craw_data_from_ZhihuDaily_and_post_article_by_user__allowing_users_to_reply_the_article_and_interact_with_other_users_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ZhihuCaffe = require('index'); // See note below*.
* var xxxSvc = new ZhihuCaffe.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ZhihuCaffe.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ZhihuCaffe.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ZhihuCaffe.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.4
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Apis model constructor.
     * @property {module:model/Apis}
     */
    Apis,

    /**
     * The Article model constructor.
     * @property {module:model/Article}
     */
    Article,

    /**
     * The Articles model constructor.
     * @property {module:model/Articles}
     */
    Articles,

    /**
     * The Replies model constructor.
     * @property {module:model/Replies}
     */
    Replies,

    /**
     * The Reply model constructor.
     * @property {module:model/Reply}
     */
    Reply,

    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag,

    /**
     * The Tags model constructor.
     * @property {module:model/Tags}
     */
    Tags,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The Users model constructor.
     * @property {module:model/Users}
     */
    Users,

    /**
    * The ArticleApi service constructor.
    * @property {module:api/ArticleApi}
    */
    ArticleApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The ReplyApi service constructor.
    * @property {module:api/ReplyApi}
    */
    ReplyApi,

    /**
    * The TagApi service constructor.
    * @property {module:api/TagApi}
    */
    TagApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
