/**
 * Zhihu_Caffe
 * Zhihu_Caffe can craw data from ZhihuDaily and post article by user,  allowing users to reply the article and interact with other users.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Apis from '../model/Apis';

/**
* Default service.
* @module api/DefaultApi
* @version 0.1.4
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getApis operation.
     * @callback module:api/DefaultApi~getApisCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Apis} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get apis list
     * Returns a list containing all apis.
     * @param {module:api/DefaultApi~getApisCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Apis}
     */
    getApis(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Apis;

      return this.apiClient.callApi(
        '/api', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
